# Generated by Django 4.2.5 on 2023-09-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_title', models.CharField(blank=True, max_length=250, null=True)),
                ('item_description', models.TextField(blank=True, max_length=9000, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='item/')),
            ],
        ),
    ]
