# Generated by Django 4.2.5 on 2023-09-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(blank=True, max_length=60, null=True)),
                ('staff_mbiemri', models.CharField(blank=True, max_length=60, null=True)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('staff_description', models.TextField(blank=True, max_length=9000, null=True)),
                ('staff_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
