# Generated by Django 4.2.5 on 2023-09-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=250, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category/')),
            ],
        ),
    ]
