# Generated by Django 4.2.5 on 2023-09-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_surname', models.CharField(blank=True, max_length=150, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_comment', models.TextField(blank=True, max_length=700, null=True)),
            ],
        ),
    ]
