# Generated by Django 4.2.5 on 2023-09-13 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0004_color_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appDjango.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_color',
            field=models.ManyToManyField(blank=True, to='appDjango.color'),
        ),
    ]
