# Generated by Django 5.0.4 on 2024-05-14 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0005_item_item_category_item_item_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_color',
        ),
    ]
