# Generated by Django 5.0.4 on 2024-05-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDjango', '0007_reserve_delete_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserve',
        ),
    ]
